version: '3'
services:

  client:
    build: ./test-client
    environment:
      # Точка для тестирования (backend)

      # - endpoint_uri=http://test-endpoint/healthcheck
      # - endpoint_uri=http://test-endpoint/slow/3
      - endpoint_uri=http://test-endpoint/cycle/error/4/4
      # - endpoint_uri=http://test-endpoint/cycle/timeout/5/5
      # - endpoint_uri=http://test-endpoint/cycle/blackhole/5/15

      # Timeout клиента, сек
      - client_max_time=30
      # Частота опроса сервера, мс
      - client_req_interval=1000
      # Выбор между параллельным (parallel) и последовательным (serial) выполнением запросов
      - resp_check_type=serial
      # Прокси, с помощью которого реализуется стратегия стабилизации работы; его можно отключить для сравнения
      # - http_proxy=http://proxy-nginx:80
      # - http_proxy=http://proxy-varnish:80
      # - http_proxy=http://proxy-squid:3128
      # Включить передачу кукисов (on, off)
      - send_cookie=off
      # Показывать заголовки ответа (on, off)
      - show_headers=off
    depends_on:
      - test-endpoint
      # - proxy-varnish
      # - proxy-nginx
      # - proxy-squid
    restart: always


  proxy-nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always


  proxy-varnish:
    build: ./varnish/
    stop_signal: SIGINT
    environment:
      - logs=off
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    restart: always



  proxy-squid:
    build: ./squid/
    restart: always
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf


  test-endpoint:
    build: ./test-endpoint
    environment:
      # Порт
      - port=80
      # Timeout endpoint сервера в мс
      - endpoint_timeout=5000
      # Включить установку кукисов
      - set_cookie=on
      # Включить установку заголовков против кеширования
      - set_no_cache_and_expired=on
      # Указать заголовок для кеширования
      - set_header_cache_control=max-age=0, stale-if-error=3600
      # Содержимое документа
      - document=n,msg,guid,now,uptime
    restart: always
